/* Generated by hardware/pcb/firmware_pins.py from the hub netlist.
 * Do not edit. Run `make firmware-pins` after any hub schematic change;
 * hardware/tests/test_firmware_pins.py fails if this drifts.
 */
#ifndef CHESSBOARD_PORT_BOARD_PINS_H
#define CHESSBOARD_PORT_BOARD_PINS_H

/* MCU GPIOs, by the net name the schematic gives them. */
#define PIN_BAT_SENSE_ADC  4
#define PIN_I2C_SCL        8
#define PIN_I2C_SDA        9
#define PIN_LED_DATA       14
#define PIN_MISO           21
#define PIN_MOSI           20
#define PIN_NFC_BUSY       3
#define PIN_NFC_CS_N       22
#define PIN_NFC_IRQ        7
#define PIN_OLED1_CS_N     23
#define PIN_OLED2_CS_N     18
#define PIN_SCLK           19
#define PIN_TEMP_SENSE_ADC 2
#define PIN_UART_RX        17
#define PIN_UART_TX        16
#define PIN_USB_CC1_ADC    0
#define PIN_USB_CC2_ADC    1

/* TCA9535 ports. A0, A1 and A2 are grounded, so the device answers at
 * 0x20. Each entry is the port index and the bit within it. */
#define EXPANDER_I2C_ADDRESS 0x20

#define EXP_BUTTON_N_PORT             0
#define EXP_BUTTON_N_BIT              6
#define EXP_CHARGE_INPUT_FAULT_N_PORT 0
#define EXP_CHARGE_INPUT_FAULT_N_BIT  5
#define EXP_LED_EN_PORT               0
#define EXP_LED_EN_BIT                4
#define EXP_LED_FAULT_N_PORT          0
#define EXP_LED_FAULT_N_BIT           7
#define EXP_NFC_GPO1_PORT             1
#define EXP_NFC_GPO1_BIT              4
#define EXP_NFC_RESET_N_PORT          0
#define EXP_NFC_RESET_N_BIT           1
#define EXP_OLED_DC_PORT              0
#define EXP_OLED_DC_BIT               2
#define EXP_OLED_RESET_N_PORT         0
#define EXP_OLED_RESET_N_BIT          3
#define EXP_SEL_RCLK_PORT             0
#define EXP_SEL_RCLK_BIT              0
#define EXP_SEL_SRCLR_N_PORT          1
#define EXP_SEL_SRCLR_N_BIT           3

#endif
