"""Generate the firmware's pin map from the authoritative hub netlist.

Hand-copying a pin map into firmware is how a schematic change becomes a
mystery at bring-up. The header this writes is generated from the same netlist
the board is routed from, and `hardware/tests/test_firmware_pins.py` fails if
the committed copy drifts from a regeneration.

Only the MCU's own GPIOs and the expander's ports are emitted. Everything else
in the netlist is passive or analog and has no firmware-visible identity.
"""

from pathlib import Path

from hardware.pcb.hub import build_hub


HEADER_PATH = (
    Path(__file__).resolve().parents[2]
    / "software"
    / "firmware"
    / "port"
    / "board_pins.h"
)

MCU_REFERENCE = "U4"
EXPANDER_REFERENCE = "U6"

# Nets that exist on the hub but reach nothing, so firmware must not be handed
# a name for them. Confirmed against the generated netlists, not the source.
#
# SEL_SRCLR_N runs from expander P1.3 to pullup R31 and stops: it is absent
# from J4's seven conductors and from matrix.py entirely, where both 74HC595
# SRCLR_N pins are tied hard to 3V3. A driver reaching for this to blank the
# selection would see its I2C write succeed and nothing happen. See
# docs/hardware/matrix.md.
DEAD_NETS = {"SEL_SRCLR_N"}

# ESP32-C6-MINI-1U module pin names, from the datasheet v1.5 Table 3-1 map in
# parts.py, to the GPIO number firmware uses. UART0 sits on IO16 and IO17,
# which the module exposes under their function names rather than as IOnn.
MODULE_PIN_TO_GPIO = {"RXD0": 17, "TXD0": 16}


def _gpio_number(module_pin_name: str) -> int | None:
    if module_pin_name in MODULE_PIN_TO_GPIO:
        return MODULE_PIN_TO_GPIO[module_pin_name]
    if not module_pin_name.startswith("IO"):
        return None
    digits = module_pin_name[2:].split("_", maxsplit=1)[0]
    return int(digits) if digits.isdigit() else None


def _connected(part_reference: str) -> list[tuple[str, str]]:
    """Return (pin name, net name) for every driven pin of one part."""
    circuit = build_hub()
    for part in circuit.parts:
        if str(part.ref) != part_reference:
            continue
        rows: list[tuple[str, str]] = []
        for pin in part.pins:
            nets = [net for net in pin.nets if net is not None]
            if not nets:
                continue
            net_name = str(nets[0].name)
            # Reviewed no-connects are still attached to SKiDL's NC net, so
            # they arrive here looking connected. They have no firmware
            # identity and must not become macros.
            if net_name.startswith("__NOCONNECT") or net_name in {"GND", "3V3"}:
                continue
            if net_name in DEAD_NETS:
                continue
            rows.append((str(pin.name), net_name))
        return rows
    raise KeyError(f"{part_reference} is not in the hub circuit")


def _mcu_rows() -> list[tuple[str, int]]:
    rows: list[tuple[str, int]] = []
    for pin_name, net_name in _connected(MCU_REFERENCE):
        gpio = _gpio_number(pin_name)
        if gpio is None:
            continue
        rows.append((net_name, gpio))
    return sorted(rows)


def _expander_rows() -> list[tuple[str, int, int]]:
    """Return (net, port, bit) for each driven expander port."""
    rows: list[tuple[str, int, int]] = []
    for pin_name, net_name in _connected(EXPANDER_REFERENCE):
        if len(pin_name) != 3 or not pin_name.startswith("P"):
            continue
        port, bit = int(pin_name[1]), int(pin_name[2])
        rows.append((net_name, port, bit))
    return sorted(rows)


def render() -> str:
    mcu = _mcu_rows()
    expander = _expander_rows()
    lines = [
        "/* Generated by hardware/pcb/firmware_pins.py from the hub netlist.",
        " * Do not edit. Run `make firmware-pins` after any hub schematic change;",
        " * hardware/tests/test_firmware_pins.py fails if this drifts.",
        " */",
        "#ifndef CHESSBOARD_PORT_BOARD_PINS_H",
        "#define CHESSBOARD_PORT_BOARD_PINS_H",
        "",
        "/* MCU GPIOs, by the net name the schematic gives them. */",
    ]
    width = max(len(name) for name, _ in mcu)
    for net, gpio in mcu:
        macro = f"PIN_{net}"
        lines.append(f"#define {macro:<{width + 4}} {gpio}")
    lines += [
        "",
        "/* TCA9535 ports. A0, A1 and A2 are grounded, so the device answers at",
        " * 0x20. Each entry is the port index and the bit within it.",
        " *",
        " * P1.3 is deliberately absent. Its net SEL_SRCLR_N reaches only a pullup:",
        " * the matrix ties both 74HC595 SRCLR_N pins to 3V3 and J4 has no conductor",
        " * for it, so the selection registers cannot be cleared by any signal. The",
        " * matrix driver must shift a known pattern at boot instead. */",
        "#define EXPANDER_I2C_ADDRESS 0x20",
        "",
    ]
    width = max(len(name) for name, _, _ in expander) + len("EXP__PORT")
    for net, port, bit in expander:
        port_macro = f"EXP_{net}_PORT"
        bit_macro = f"EXP_{net}_BIT"
        lines.append(f"#define {port_macro:<{width}} {port}")
        lines.append(f"#define {bit_macro:<{width}} {bit}")
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def main() -> None:
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {HEADER_PATH}")


if __name__ == "__main__":
    main()
